# Generated by Django 3.1.4 on 2021-12-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('house', models.CharField(max_length=200)),
                ('polled', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
